- hosts: frontends
  gather_facts: false
  tasks:
  - name: Smoke test for prod env
    uri:
      url: "http://{{ item }}"
      return_content: yes
    with_items:
      - "{{ inventory_hostname }}"
    register: webpage
    failed_when: "'Ansible has done its job' not in webpage.content"
    tags:
      - aws.smoke

